source 'http://ruby.taobao.org'

gem 'rails', '3.2.9'
#gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :production do
  gem 'mysql2'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',    '~> 3.2.3'
  gem 'coffee-rails',  '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'execjs'
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

#gem 'jquery-rails'
gem 'jquery-rails', '~> 2.3.0'

# To use ActiveModel has_secure_password
#gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'debugger'

#gem 'will_paginate', '~> 3.0'
gem 'kaminari'
#gem "activeadmin", git: "https://github.com/gregbell/active_admin"

#START:plugins
#START_HIGHLIGHT
gem 'activemerchant'
#START_HIGHLIGHT
gem 'haml', '~> 3.1.1'
#END_HIGHLIGHT
#END_HIGHLIGHT
#END:plugins

gem "paperclip", "~> 3.0"
gem 'rmagick'
